//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neo.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NEO 的本地化字符串。
        /// </summary>
        internal static string AboutMessage {
            get {
                return ResourceManager.GetString("AboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version: 的本地化字符串。
        /// </summary>
        internal static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to add smart contract, corresponding private key missing in this wallet. 的本地化字符串。
        /// </summary>
        internal static string AddContractFailedMessage {
            get {
                return ResourceManager.GetString("AddContractFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change password successful. 的本地化字符串。
        /// </summary>
        internal static string ChangePasswordSuccessful {
            get {
                return ResourceManager.GetString("ChangePasswordSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please choose command! 的本地化字符串。
        /// </summary>
        internal static string ChooseCommand {
            get {
                return ResourceManager.GetString("ChooseCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please choose script hash! 的本地化字符串。
        /// </summary>
        internal static string ChooseScriptHash {
            get {
                return ResourceManager.GetString("ChooseScriptHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirmation 的本地化字符串。
        /// </summary>
        internal static string DeleteAddressConfirmationCaption {
            get {
                return ResourceManager.GetString("DeleteAddressConfirmationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upon deletion, assets in these addresses will be permanently lost, are you sure to proceed? 的本地化字符串。
        /// </summary>
        internal static string DeleteAddressConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteAddressConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Assets cannot be recovered once deleted, are you sure to delete the assets? 的本地化字符串。
        /// </summary>
        internal static string DeleteAssetConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteAssetConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirmation 的本地化字符串。
        /// </summary>
        internal static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter remark here, which will be recorded on the blockchain 的本地化字符串。
        /// </summary>
        internal static string EnterRemarkMessage {
            get {
                return ResourceManager.GetString("EnterRemarkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transaction Remark 的本地化字符串。
        /// </summary>
        internal static string EnterRemarkTitle {
            get {
                return ResourceManager.GetString("EnterRemarkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execution terminated in fault state. 的本地化字符串。
        /// </summary>
        internal static string ExecutionFailed {
            get {
                return ResourceManager.GetString("ExecutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expired 的本地化字符串。
        /// </summary>
        internal static string ExpiredCertificate {
            get {
                return ResourceManager.GetString("ExpiredCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed 的本地化字符串。
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import Watch-Only Address 的本地化字符串。
        /// </summary>
        internal static string ImportWatchOnlyAddress {
            get {
                return ResourceManager.GetString("ImportWatchOnlyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transaction initiated, but the signature is incomplete. 的本地化字符串。
        /// </summary>
        internal static string IncompletedSignatureMessage {
            get {
                return ResourceManager.GetString("IncompletedSignatureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incomplete signature 的本地化字符串。
        /// </summary>
        internal static string IncompletedSignatureTitle {
            get {
                return ResourceManager.GetString("IncompletedSignatureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have cancelled the certificate installation. 的本地化字符串。
        /// </summary>
        internal static string InstallCertificateCancel {
            get {
                return ResourceManager.GetString("InstallCertificateCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install the certificate 的本地化字符串。
        /// </summary>
        internal static string InstallCertificateCaption {
            get {
                return ResourceManager.GetString("InstallCertificateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NEO must install Onchain root certificate to validate assets on the blockchain, install it now? 的本地化字符串。
        /// </summary>
        internal static string InstallCertificateText {
            get {
                return ResourceManager.GetString("InstallCertificateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insufficient funds, transaction cannot be initiated. 的本地化字符串。
        /// </summary>
        internal static string InsufficientFunds {
            get {
                return ResourceManager.GetString("InsufficientFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid 的本地化字符串。
        /// </summary>
        internal static string InvalidCertificate {
            get {
                return ResourceManager.GetString("InvalidCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Migrate Wallet 的本地化字符串。
        /// </summary>
        internal static string MigrateWalletCaption {
            get {
                return ResourceManager.GetString("MigrateWalletCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opening wallet files in older versions, update to newest format?
        ///Note: updated files cannot be openned by clients in older versions! 的本地化字符串。
        /// </summary>
        internal static string MigrateWalletMessage {
            get {
                return ResourceManager.GetString("MigrateWalletMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wallet files relocated. Old files have been auto-saved at:  的本地化字符串。
        /// </summary>
        internal static string MigrateWalletSucceedMessage {
            get {
                return ResourceManager.GetString("MigrateWalletSucceedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password Incorrect 的本地化字符串。
        /// </summary>
        internal static string PasswordIncorrect {
            get {
                return ResourceManager.GetString("PasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data broadcast success, the hash is shown as follows: 的本地化字符串。
        /// </summary>
        internal static string RelaySuccessText {
            get {
                return ResourceManager.GetString("RelaySuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Broadcast Success 的本地化字符串。
        /// </summary>
        internal static string RelaySuccessTitle {
            get {
                return ResourceManager.GetString("RelaySuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Raw: 的本地化字符串。
        /// </summary>
        internal static string RelayTitle {
            get {
                return ResourceManager.GetString("RelayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transaction sent, TXID: 的本地化字符串。
        /// </summary>
        internal static string SendTxSucceedMessage {
            get {
                return ResourceManager.GetString("SendTxSucceedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transaction successful 的本地化字符串。
        /// </summary>
        internal static string SendTxSucceedTitle {
            get {
                return ResourceManager.GetString("SendTxSucceedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The private key that can sign the data is not found. 的本地化字符串。
        /// </summary>
        internal static string SigningFailedKeyNotFoundMessage {
            get {
                return ResourceManager.GetString("SigningFailedKeyNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You must input JSON object pending signature data. 的本地化字符串。
        /// </summary>
        internal static string SigningFailedNoDataMessage {
            get {
                return ResourceManager.GetString("SigningFailedNoDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System 的本地化字符串。
        /// </summary>
        internal static string SystemIssuer {
            get {
                return ResourceManager.GetString("SystemIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Validation failed, the counterparty falsified the transaction content! 的本地化字符串。
        /// </summary>
        internal static string TradeFailedFakeDataMessage {
            get {
                return ResourceManager.GetString("TradeFailedFakeDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Validation failed, the counterparty generated illegal transaction content! 的本地化字符串。
        /// </summary>
        internal static string TradeFailedInvalidDataMessage {
            get {
                return ResourceManager.GetString("TradeFailedInvalidDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Validation failed, invalid transaction or unsynchronized blockchain, please try again when synchronized! 的本地化字符串。
        /// </summary>
        internal static string TradeFailedNoSyncMessage {
            get {
                return ResourceManager.GetString("TradeFailedNoSyncMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Need Signature 的本地化字符串。
        /// </summary>
        internal static string TradeNeedSignatureCaption {
            get {
                return ResourceManager.GetString("TradeNeedSignatureCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transaction generated, please send the following information to the counterparty for signing: 的本地化字符串。
        /// </summary>
        internal static string TradeNeedSignatureMessage {
            get {
                return ResourceManager.GetString("TradeNeedSignatureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trade Request 的本地化字符串。
        /// </summary>
        internal static string TradeRequestCreatedCaption {
            get {
                return ResourceManager.GetString("TradeRequestCreatedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transaction request generated, please send it to the counterparty or merge it with the counterparty&apos;s request. 的本地化字符串。
        /// </summary>
        internal static string TradeRequestCreatedMessage {
            get {
                return ResourceManager.GetString("TradeRequestCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Trade Success 的本地化字符串。
        /// </summary>
        internal static string TradeSuccessCaption {
            get {
                return ResourceManager.GetString("TradeSuccessCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transaction sent, this is the TXID: 的本地化字符串。
        /// </summary>
        internal static string TradeSuccessMessage {
            get {
                return ResourceManager.GetString("TradeSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 unconfirmed 的本地化字符串。
        /// </summary>
        internal static string Unconfirmed {
            get {
                return ResourceManager.GetString("Unconfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 unknown issuer 的本地化字符串。
        /// </summary>
        internal static string UnknownIssuer {
            get {
                return ResourceManager.GetString("UnknownIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blockchain unsynchronized, transaction cannot be sent. 的本地化字符串。
        /// </summary>
        internal static string UnsynchronizedBlock {
            get {
                return ResourceManager.GetString("UnsynchronizedBlock", resourceCulture);
            }
        }
    }
}
